name: simple_gym_control_free
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  bcrypt: ^1.1.3
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  get: ^4.6.1
  intl: ^0.17.0
  responsive_design: ^0.1.5
  sqflite: ^2.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  lint: ^1.8.2

flutter:
  uses-material-design: true

  assets:
    - assets/db/
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/simple_gym_control_icon.png"
